#!/usr/bin/env python3
"""Export a Zuma VDAC2 FT812 playback bundle.

The bundle is meant for a Bridgetek/EVE-side harness: it contains a RAM_G image
assembled from current converted assets plus command FIFO frames generated by
the Z80 renderer. It does not edit game sources.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
CONV = ROOT / "Graphics" / "Converted"
RAM_G_SIZE = 1024 * 1024
CMD_ADDRESS_PTR = 0x5E00

sys.path.insert(0, str(HERE))
from zuma_full_z80_emulator import ZumaFullZ80Emulator  # noqa: E402


def parse_equ(path: Path) -> dict[str, int]:
    out: dict[str, int] = {}
    rx = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s+EQU\s+(.+?)(?:\s*;.*)?$")
    text = path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        m = rx.match(line)
        if not m:
            continue
        name, expr = m.groups()
        expr = expr.replace("#", "0x")
        try:
            out[name] = int(eval(expr, {"__builtins__": {}}, out))
        except Exception:
            pass
    return out


def put(ram: bytearray, addr: int, data: bytes, label: str, manifest: list[dict]) -> None:
    end = addr + len(data)
    if addr < 0 or end > len(ram):
        raise ValueError(f"{label}: RAM_G range out of bounds: 0x{addr:06X}..0x{end:06X}")
    ram[addr:end] = data
    manifest.append({"label": label, "addr": addr, "size": len(data), "end": end})


def read_exact_or_pad(path: Path, size: int) -> bytes:
    data = path.read_bytes()
    if len(data) > size:
        raise ValueError(f"{path.name}: {len(data)} bytes > expected block {size}")
    return data + bytes(size - len(data))


def build_ram_g(equ: dict[str, int]) -> tuple[bytes, list[dict]]:
    ram = bytearray(RAM_G_SIZE)
    manifest: list[dict] = []

    def add_file(label: str, addr_name: str, filename: str, limit: int | None = None) -> None:
        p = CONV / filename
        if not p.exists():
            print(f"  [skip] {label}: {filename} missing (RAM_G zero-filled; DL count unaffected)")
            return
        data = p.read_bytes()
        if limit is not None:
            data = data[:limit]
        put(ram, equ[addr_name], data, label, manifest)

    def add_pages(label: str, addr_name: str, pattern: str, count: int) -> None:
        addr = equ[addr_name]
        for i in range(count):
            p = CONV / (pattern % i)
            if not p.exists():
                print(f"  [skip] {label}_{i:02d}: {pattern % i} missing (RAM_G zero-filled)")
                continue
            put(ram, addr + i * 0x4000, p.read_bytes(), f"{label}_{i:02d}", manifest)

    add_pages("bg_paletted", "BG_RAMG_ADDR", "bg_paletted_p%02d.bin", equ["BG_PAGE_COUNT"])
    add_file("bg_palette_argb4", "BG_PALETTE_RAMG", "bg_palette_argb4.bin", 512)
    if equ.get("BALLS_ARGB4_ENABLED", 0):
        add_pages("balls_argb4", "BALLS_RAMG_ADDR", "balls_native_p%02d.bin", equ["BALLS_PAGE_COUNT"])
    else:
        add_pages("balls_paletted", "BALLS_RAMG_ADDR", "balls_atlas_paletted_p%02d.bin", equ["BALLS_PAGE_COUNT"])
        add_file("balls_palette_argb4", "BALLS_PALETTE_RAMG", "balls_palette_argb4.bin", 512)

    frog_pages = [
        ("frog_body_paletted", "FROG_RAMG_ADDR", "frog_paletted.bin"),
        ("frog_plate_paletted", "PLATE_RAMG_ADDR", "frog_plate_paletted.bin"),
        ("frog_tongue_paletted", "TONGUE_RAMG_ADDR", "frog_tongue_paletted.bin"),
        ("frog_overlay_paletted", "OVERLAY_RAMG_ADDR", "frog_overlay_paletted.bin"),
    ]
    for label, addr_name, name in frog_pages:
        put(ram, equ[addr_name], read_exact_or_pad(CONV / name, 0x4000), label, manifest)
    add_file("frog_palette_argb4", "FROG_PALETTE_RAMG", "frog_palette_argb4.bin", 512)
    add_file("frog_plate_palette_argb4", "PLATE_PALETTE_RAMG", "frog_plate_palette_argb4.bin", 512)
    add_file("frog_tongue_palette_argb4", "TONGUE_PALETTE_RAMG", "frog_tongue_palette_argb4.bin", 512)
    add_file("frog_overlay_palette_argb4", "OVERLAY_PALETTE_RAMG", "frog_overlay_palette_argb4.bin", 512)

    add_pages("killzone", "KZ_RAMG_ADDR", "killzone_p%02d.bin", 6)
    add_pages("destroy", "DESTROY_RAMG_ADDR", "destroy_atlas_p%02d.bin", 4)
    put(ram, equ["CURSOR_RAMG_ADDR"], (CONV / "cursor_p00.bin").read_bytes(), "cursor", manifest)

    # Text/sparkle assets are only stored compressed in the current tree. They are
    # irrelevant for the frame-strip tearing A/B in PLAY, so leave them zeroed if
    # raw files are absent.
    optional = [
        ("text_gameover", "TEXT_GAMEOVER_RAMG", "text_gameover.bin"),
        ("text_level11", "TEXT_LEVEL11_RAMG", "text_level11.bin"),
        ("text_spiraldoom", "TEXT_SPIRALDOOM_RAMG", "text_spiraldoom.bin"),
        ("sparkle", "SPARKLE_RAMG", "sparkle.bin"),
    ]
    for label, addr_name, name in optional:
        path = CONV / name
        if path.exists():
            put(ram, equ[addr_name], path.read_bytes(), label, manifest)

    add_file("frame_palette_argb4", "FRAME_PAL_RAMG", "frame_palette_argb4.bin", 512)
    put(ram, equ["FRAME_TOP_RAMG"], read_exact_or_pad(CONV / "frame_top_p0.bin", 0x4000), "frame_top_p0", manifest)
    put(ram, equ["FRAME_TOP_RAMG"] + 0x4000, read_exact_or_pad(CONV / "frame_top_p1.bin", 0x4000), "frame_top_p1", manifest)
    put(ram, equ["FRAME_BOT_RAMG"], read_exact_or_pad(CONV / "frame_bot.bin", 0x4000), "frame_bot", manifest)
    put(ram, equ["FRAME_LEFT_RAMG"], read_exact_or_pad(CONV / "frame_left.bin", 0x4000), "frame_left", manifest)
    put(ram, equ["FRAME_RIGHT_RAMG"], read_exact_or_pad(CONV / "frame_right.bin", 0x4000), "frame_right", manifest)

    # --- HUD: life_frog + dialog (v028) ---
    hud_assets = [
        ("life_frog", "LIFE_FROG_RAMG", "life_frog.bin", None),
        ("hud_palette", "HUD_PALETTE_RAMG", "hud_palette_argb4.bin", 512),
        ("hud_menu_atlas", "HUD_MENU_RAMG", "hud_menu_atlas.bin", None),
        ("hud_progress_atlas", "HUD_PROGRESS_RAMG", "hud_progress_atlas.bin", None),
        ("dialog_palette", "DIALOG_PALETTE_RAMG", "dialog_palette_argb4.bin", 512),
        ("dlg_mm_normal", "DIALOG_MM_NORMAL_RAMG", "dialog_main_menu_normal.bin", None),
        ("dlg_mm_hover", "DIALOG_MM_HOVER_RAMG", "dialog_main_menu_hover.bin", None),
        ("dlg_mm_pressed", "DIALOG_MM_PRESSED_RAMG", "dialog_main_menu_pressed.bin", None),
        ("dlg_play_normal", "DIALOG_PLAY_NORMAL_RAMG", "dialog_play_normal.bin", None),
        ("dlg_play_hover", "DIALOG_PLAY_HOVER_RAMG", "dialog_play_hover.bin", None),
        ("dlg_play_pressed", "DIALOG_PLAY_PRESSED_RAMG", "dialog_play_pressed.bin", None),
        ("dlg_txt_gameover", "DLG_TXT_GAMEOVER_RAMG", "text_dialog_gameover.bin", None),
        ("dlg_txt_2lives", "DLG_TXT_2LIVES_RAMG", "text_dialog_2lives.bin", None),
        ("dlg_txt_1lives", "DLG_TXT_1LIVES_RAMG", "text_dialog_1lives.bin", None),
    ]
    for label, addr_name, fname, limit in hud_assets:
        if addr_name not in equ:
            continue
        p = CONV / fname
        if not p.exists():
            continue
        data = p.read_bytes()
        if limit is not None:
            data = data[:limit]
        put(ram, equ[addr_name], data, label, manifest)

    # --- Dialog frame chunks (8×16K raw) ---
    if "DIALOG_FRAME_RAMG" in equ:
        base = equ["DIALOG_FRAME_RAMG"]
        for i in range(8):
            p = CONV / f"dialog_frame_p{i:02d}.bin"
            if p.exists():
                put(ram, base + i * 0x4000, read_exact_or_pad(p, 0x4000), f"dialog_frame_p{i:02d}", manifest)

    # --- Native font atlas ---
    if "FONT_NATIVE_RAMG" in equ:
        p = CONV / "font_native_atlas.bin"
        if p.exists():
            put(ram, equ["FONT_NATIVE_RAMG"], p.read_bytes(), "font_native_atlas", manifest)

    # --- Cancun8 font atlas ---
    if "FONT_CANCUN8_RAMG" in equ:
        p = CONV / "font_cancun8_atlas.bin"
        if p.exists():
            put(ram, equ["FONT_CANCUN8_RAMG"], p.read_bytes(), "font_cancun8_atlas", manifest)

    return bytes(ram), manifest


def write_u32_to_mem(emu: ZumaFullZ80Emulator, ptr: int, value: int) -> int:
    for i in range(4):
        emu.mem.write(ptr + i, (value >> (8 * i)) & 0xFF)
    return ptr + 4


def draw_full_command_frame(emu: ZumaFullZ80Emulator) -> bytes:
    ptr = CMD_ADDRESS_PTR
    ptr = write_u32_to_mem(emu, ptr, 0xFFFFFF00)  # CMD_DLSTART
    ptr = write_u32_to_mem(emu, ptr, (0x27 << 24) | 4)  # VERTEX_FORMAT(4)
    ptr = write_u32_to_mem(emu, ptr, (0x02 << 24) | 0x102030)  # CLEAR_COLOR_RGB
    ptr = write_u32_to_mem(emu, ptr, (0x26 << 24) | 0x07)  # CLEAR(1,1,1)
    emu.set_word(emu.sym["FT.Coprocessor.BufferPtr"], ptr)
    emu.call(emu.sym["Core.ZL_DrawFrame"])
    ptr = emu.get_word(emu.sym["FT.Coprocessor.BufferPtr"])
    ptr = write_u32_to_mem(emu, ptr, 0x00000000)  # DISPLAY
    used = (ptr - CMD_ADDRESS_PTR) & 0xFFFF
    return emu.mem.read_block(CMD_ADDRESS_PTR, used)


def advance_logic(emu: ZumaFullZ80Emulator) -> None:
    for name in (
        "Core.ZL_AimUpdate",
        "Core.ZL_SmoothMouse",
        "Core.Frog_Update",
        "Core.VDC_Update",
        "Core.Bullet_Update",
        "Core.Bullet_CheckCollision",
    ):
        if name in emu.sym:
            emu.call(emu.sym[name])
    fc = emu.sym["Core.ZL_FrameCounter"]
    emu.set_word(fc, (emu.get_word(fc) + 1) & 0xFFFF)


def export_frames(out_dir: Path, frames: list[int], force_dialog: int | None = None,
                  force_lives: int | None = None) -> list[dict]:
    emu = ZumaFullZ80Emulator(ROOT)
    emu.game_init()
    wanted = set(frames)
    records: list[dict] = []
    last = max(wanted) if wanted else -1
    for frame in range(last + 1):
        if frame in wanted:
            # Optionally force dialog state for visualizing GAMEOVER overlay.
            if force_dialog is not None and "Core.VDC_DialogState" in emu.sym:
                emu.mem.write(emu.sym["Core.VDC_DialogState"], force_dialog)
            if force_lives is not None and "Core.VDC_Lives" in emu.sym:
                emu.mem.write(emu.sym["Core.VDC_Lives"], force_lives)
            data = draw_full_command_frame(emu)
            name = f"cmd_frame_{frame:04d}.bin"
            (out_dir / name).write_bytes(data)
            records.append({
                "frame": frame,
                "file": name,
                "cmd_bytes": len(data),
                "game_state": emu.get_byte(emu.sym["Core.VDC_GameState"]),
                "slots_len": emu.get_byte(emu.sym["Core.VDC_SlotsLen"]),
            })
        advance_logic(emu)
    return records


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--out",
        default=str(ROOT / "Diagnostics" / "FT812Bundles" / "_ft812_bundle"),
    )
    ap.add_argument("--frames", default="0,240,433,500,650")
    ap.add_argument("--force-dialog", type=int, default=None, help="Force VDC_DialogState (0/1/2) per snapshot")
    ap.add_argument("--force-lives", type=int, default=None, help="Force VDC_Lives (0..3) per snapshot")
    args = ap.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    equ = parse_equ(ROOT / "Source" / "ASM" / "main.asm")
    ram_g, ram_manifest = build_ram_g(equ)
    (out_dir / "ram_g.bin").write_bytes(ram_g)
    frame_nums = [int(x.strip(), 0) for x in args.frames.split(",") if x.strip()]
    frame_manifest = export_frames(out_dir, frame_nums, force_dialog=args.force_dialog, force_lives=args.force_lives)
    manifest = {
        "project": str(ROOT),
        "ram_g_file": "ram_g.bin",
        "ram_g_size": len(ram_g),
        "cmd_address_ptr": CMD_ADDRESS_PTR,
        "assets": ram_manifest,
        "frames": frame_manifest,
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"wrote {out_dir}")
    for rec in frame_manifest:
        print(f"frame {rec['frame']:4d}: state={rec['game_state']} slots={rec['slots_len']} cmd={rec['cmd_bytes']} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
