"""Build ZUMALVL.PAK — external level pack streamed via WC ZiFi LOAD512.

Layout (512-byte sectors):
  Sector 0          : Header   { magic "ZLVP", version=1, level_count=22, sector_size=512 }
  Sector 1          : TOC[22]  × 20 bytes each (bg/pal/track/title/preview off+size)
  Sector 2..N       : data blob, per-level: bg -> pal -> track -> title -> preview
                      each section sector-aligned (zero-padded tail)
                      missing section => off=0xFFFF in TOC
                      track sections are Track V4 + bullet trajectory table:
                        sector 0: metadata "ZTV4" + chain sample/page counts
                        then pure 16K pages of 8-byte baked render samples
                        then one 16K "ZBT1" page for bullet collision events
                      runtime maps up to four pages from the same section.

Currently:
  L01..L22              -> all five sections present when generated by
                           make_all_level_pack_assets.py

Pack lands in `Build/ZUMALVL.PAK`. Verified via internal _verify().
"""
from __future__ import annotations

import struct
import sys
from pathlib import Path
from typing import Optional

from make_bullet_trajectory_tables import build_level_table as build_bullet_table

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
CONVERTED = ROOT / "Graphics" / "levels" / "Converted"
PACK_ASSETS = CONVERTED / "pack"
OUT = ROOT / "Build" / "ZUMALVL.PAK"

SECTOR = 512
LEVEL_COUNT = 22

# section indexes
S_BG, S_PAL, S_TRACK, S_TITLE, S_PREVIEW = range(5)
SECTION_NAMES = ["bg", "pal", "track", "title", "preview"]


def asset_files_for_level(level_idx0: int) -> dict[int, list[Path]]:
    """Return {section_index: [Path]} for level pack assets; empty dict if absent."""
    n = level_idx0 + 1
    return {
        S_BG:      [PACK_ASSETS / f"bg_l{n:02d}_paletted_p{p:02d}.bin" for p in range(8)],
        S_PAL:     [PACK_ASSETS / f"bg_l{n:02d}_palette_argb4.bin"],
        S_TRACK:   [PACK_ASSETS / f"track_l{n:02d}_640.bin"],
        S_TITLE:   [PACK_ASSETS / f"text_l{n:02d}_zx7.bin"],
        S_PREVIEW: [PACK_ASSETS / f"level_select_preview_l{n:02d}_p{p:02d}.bin" for p in range(8)],
    }


def track_files_for_level(level_idx0: int) -> list[Path]:
    n = level_idx0 + 1
    paths = [PACK_ASSETS / f"track_l{n:02d}_640.bin"]
    second = PACK_ASSETS / f"track_l{n:02d}_2_640.bin"
    if second.exists():
        paths.append(second)
    return paths


def read_concat(paths: list[Path]) -> Optional[bytes]:
    if not paths:
        return None
    blob = bytearray()
    for p in paths:
        if not p.exists():
            return None
        blob += p.read_bytes()
    return bytes(blob)


def sectors_for(size_bytes: int) -> int:
    return (size_bytes + SECTOR - 1) // SECTOR


def pad_to_sector(blob: bytes) -> bytes:
    pad = (-len(blob)) % SECTOR
    return blob + b"\x00" * pad


# --- track v4 ---------------------------------------------------------------
# Runtime track pages are pure arrays of 8-byte samples:
#   +0..3 exact FT812 VERTEX2F command (little-endian)
#   +4    tangent
#   +5    flags
#   +6    baked spin12 = floor(sample*61/256) mod 12
#   +7    meta: bit0=Vx sign, bit1=Vy sign, bit2=visible by legacy cull
#
# A 16K page holds exactly 2048 samples. The track section starts with one 512B
# metadata sector ("ZTV4", counts and page counts), followed by all chain1 pages
# then all chain2 pages. Source track_l*_640.bin files remain old 6-byte
# 640x480-space assets; only the packed PAK data is converted.
PAGE = 16384
TRACK_SRC_HDR = 2
TRACK_SRC_REC = 6
TRACK_V2_REC = 8
TRACK_V2_SAMPLES_PER_PAGE = PAGE // TRACK_V2_REC
TRACK_V2_MAGIC = b"ZTV4"
TRACK_BULLET_MAGIC = b"ZBT1"
TRACK_V2_MAX_PAGES = 4
TRACK_V2_BALL_HALF = 26
TRACK_BULLET_PAGES = 1
TRACK_SPIN12_K = 61
TRACK_SPIN12_PHASES = 12
TRACK_V4_META_VISIBLE = 0x01
TRACK_V4_META_VY_SIGN = 0x40
TRACK_V4_META_VX_SIGN = 0x80
TRACK_V4_CULL_MIN = -832
TRACK_V4_CULL_X_MAX = 0x4000
TRACK_V4_CULL_Y_MAX = 0x3000

# --- 1024x768 upscale: scale stored sample X/Y x1.6 (640->1024, 480->768) ----
# Source track bins (track_l*_640.bin) stay in 640x480 space; we scale ONLY the
# coordinates packed into the PAK, so the running game gets 1024-space ball
# positions for free. Sample COUNT is unchanged -> VDC physics (speed in
# samples/frame, CELL_SIZE in samples) and tangent bytes are untouched, so the
# tuned feel is preserved exactly. Anything that consumes ball X/Y at runtime
# (bullet collision, frog, killzone) must also be in 1024-space.
TRACK_SCALE_NUM = 8     # x1.6 = 8/5
TRACK_SCALE_DEN = 5


def scale_track_samples(blob: Optional[bytes]) -> Optional[bytes]:
    """Return an old-format track blob (header + N*6) with X,Y scaled x8/5."""
    if blob is None:
        return None
    count = struct.unpack_from("<H", blob, 0)[0]
    out = bytearray(blob[:TRACK_SRC_HDR])
    off = TRACK_SRC_HDR
    for _ in range(count):
        x, y, tan, flags = struct.unpack_from("<hhBB", blob, off)
        x = int(round(x * TRACK_SCALE_NUM / TRACK_SCALE_DEN))
        y = int(round(y * TRACK_SCALE_NUM / TRACK_SCALE_DEN))
        out += struct.pack("<hhBB", x, y, tan, flags)
        off += TRACK_SRC_REC
    return bytes(out)


def track_v4_visible(vx: int, vy: int) -> bool:
    """Return the exact legacy cache-builder cull result for baked corners."""
    return (
        TRACK_V4_CULL_MIN <= vx < TRACK_V4_CULL_X_MAX
        and TRACK_V4_CULL_MIN <= vy < TRACK_V4_CULL_Y_MAX
    )


def pack_vertex2f(vx: int, vy: int) -> int:
    """Pack signed 16-bit baked corners into the exact FT812 VERTEX2F word."""
    if not (-0x8000 <= vx <= 0x7FFF and -0x8000 <= vy <= 0x7FFF):
        raise ValueError(f"VERTEX2F source outside signed16: ({vx}, {vy})")
    return 0x40000000 | ((vx & 0x7FFF) << 15) | (vy & 0x7FFF)


def encode_track_v4_record(vx: int, vy: int, tangent: int, flags: int, spin12: int) -> bytes:
    meta = 0
    if vx < 0:
        meta |= TRACK_V4_META_VX_SIGN
    if vy < 0:
        meta |= TRACK_V4_META_VY_SIGN
    if track_v4_visible(vx, vy):
        meta |= TRACK_V4_META_VISIBLE
    return struct.pack("<IBBBB", pack_vertex2f(vx, vy), tangent, flags, spin12, meta)


def decode_track_v4_vertex(record: bytes) -> tuple[int, int]:
    """Recover the original signed16 Vx/Vy exactly from one Track V4 record."""
    if len(record) != TRACK_V2_REC:
        raise ValueError(f"Track V4 record must be {TRACK_V2_REC} bytes")
    word = struct.unpack_from("<I", record, 0)[0]
    meta = record[7]
    vx = (word >> 15) & 0x7FFF
    vy = word & 0x7FFF
    if meta & TRACK_V4_META_VX_SIGN:
        vx -= 0x8000
    if meta & TRACK_V4_META_VY_SIGN:
        vy -= 0x8000
    return vx, vy


def encode_track_v2_pages(blob: Optional[bytes]) -> tuple[int, list[bytes]]:
    if blob is None:
        return 0, []
    count = struct.unpack_from("<H", blob, 0)[0]
    samples = bytearray()
    off = TRACK_SRC_HDR
    for sample_index in range(count):
        x, y, tan, flags = struct.unpack_from("<hhBB", blob, off)
        vx = (x - TRACK_V2_BALL_HALF) * 16
        vy = (y - TRACK_V2_BALL_HALF) * 16
        spin12 = ((sample_index * TRACK_SPIN12_K) >> 8) % TRACK_SPIN12_PHASES
        samples += encode_track_v4_record(vx, vy, tan, flags, spin12)
        off += TRACK_SRC_REC
    pages: list[bytes] = []
    for page_off in range(0, len(samples), PAGE):
        page = bytes(samples[page_off : page_off + PAGE])
        pages.append(page + b"\x00" * (PAGE - len(page)))
    if not pages:
        pages.append(b"\x00" * PAGE)
    return count, pages


def make_track_v2_metadata(
    count1: int,
    pages1: int,
    count2: int,
    pages2: int,
    bullet_pages: int,
    bullet_used: int,
) -> bytes:
    meta = bytearray(SECTOR)
    meta[0:4] = TRACK_V2_MAGIC
    struct.pack_into("<H", meta, 4, count1)
    meta[6] = pages1
    struct.pack_into("<H", meta, 7, count2)
    meta[9] = pages2
    meta[10] = TRACK_V2_REC
    struct.pack_into("<H", meta, 11, TRACK_V2_SAMPLES_PER_PAGE)
    meta[13:17] = TRACK_BULLET_MAGIC
    meta[17] = bullet_pages
    struct.pack_into("<H", meta, 18, bullet_used)
    return bytes(meta)


def read_track_blob(level_idx0: int) -> Optional[bytes]:
    paths = track_files_for_level(level_idx0)
    if not paths or not paths[0].exists():
        return None
    first = scale_track_samples(paths[0].read_bytes())
    count1, pages1 = encode_track_v2_pages(first)
    count2, pages2 = 0, []
    second = None
    if len(paths) > 1:
        second = scale_track_samples(paths[1].read_bytes())
        count2, pages2 = encode_track_v2_pages(second)

    total_pages = len(pages1) + len(pages2)
    if total_pages > TRACK_V2_MAX_PAGES:
        raise ValueError(
            f"L{level_idx0 + 1:02d}: Track V2 supports {TRACK_V2_MAX_PAGES} runtime "
            f"pages, got {total_pages} ({len(pages1)} + {len(pages2)})"
        )
    bullet = build_bullet_table(level_idx0, [b for b in (first, second) if b is not None])
    if len(bullet) != PAGE or bullet[0:4] != TRACK_BULLET_MAGIC:
        raise ValueError(f"L{level_idx0 + 1:02d}: bad bullet trajectory table")
    bullet_used = struct.unpack_from("<H", bullet, 12)[0]
    meta = make_track_v2_metadata(
        count1, len(pages1), count2, len(pages2), TRACK_BULLET_PAGES, bullet_used
    )
    return meta + b"".join(pages1 + pages2) + bullet


def build() -> tuple[bytes, list[dict]]:
    # Stage 1: read all assets, compute per-level section sizes
    level_data: list[list[Optional[bytes]]] = []
    for li in range(LEVEL_COUNT):
        assets = asset_files_for_level(li)
        row: list[Optional[bytes]] = []
        for si in range(5):
            if si == S_TRACK:
                blob = read_track_blob(li)
            else:
                blob = read_concat(assets.get(si, []))
            row.append(blob)
        level_data.append(row)

    # Stage 2: layout — assign sector offsets, in order: header(1) + toc(1) + data
    cursor = 2  # first data sector after header(0) + toc(1)
    toc: list[dict] = []
    for li, row in enumerate(level_data):
        entry = {"level": li + 1}
        for si in range(5):
            name = SECTION_NAMES[si]
            blob = row[si]
            if blob is None:
                entry[f"{name}_off"]  = 0xFFFF
                entry[f"{name}_size"] = 0
            else:
                size_sec = sectors_for(len(blob))
                entry[f"{name}_off"]  = cursor
                entry[f"{name}_size"] = size_sec
                cursor += size_sec
        toc.append(entry)

    # Stage 3: emit bytes
    out = bytearray()
    # sector 0: header
    header = bytearray(SECTOR)
    header[0:4] = b"ZLVP"
    header[4]   = 1                 # version
    header[5]   = LEVEL_COUNT
    struct.pack_into("<H", header, 6, SECTOR)
    out += bytes(header)

    # sector 1: TOC
    toc_blob = bytearray()
    for e in toc:
        toc_blob += struct.pack(
            "<HHHHHHHHHH",
            e["bg_off"], e["bg_size"],
            e["pal_off"], e["pal_size"],
            e["track_off"], e["track_size"],
            e["title_off"], e["title_size"],
            e["preview_off"], e["preview_size"],
        )
    out += pad_to_sector(bytes(toc_blob))
    assert len(out) == 2 * SECTOR, f"header+toc != 1024, got {len(out)}"

    # sectors 2..N: data blob in TOC order
    for li, row in enumerate(level_data):
        for si in range(5):
            blob = row[si]
            if blob is None:
                continue
            out += pad_to_sector(blob)

    return bytes(out), toc


def _verify(pack: bytes, toc: list[dict]) -> None:
    """Re-extract each level section, byte-compare against source files."""
    # magic
    assert pack[0:4] == b"ZLVP"
    assert pack[4] == 1
    assert pack[5] == LEVEL_COUNT
    assert struct.unpack_from("<H", pack, 6)[0] == SECTOR

    # parse TOC straight from pack
    parsed = []
    base = SECTOR  # sector 1
    for li in range(LEVEL_COUNT):
        vals = struct.unpack_from("<HHHHHHHHHH", pack, base + li * 20)
        parsed.append({
            "bg_off": vals[0], "bg_size": vals[1],
            "pal_off": vals[2], "pal_size": vals[3],
            "track_off": vals[4], "track_size": vals[5],
            "title_off": vals[6], "title_size": vals[7],
            "preview_off": vals[8], "preview_size": vals[9],
        })

    # cross-check vs builder's toc
    for li in range(LEVEL_COUNT):
        for f in ("bg_off","bg_size","pal_off","pal_size","track_off","track_size",
                  "title_off","title_size","preview_off","preview_size"):
            assert parsed[li][f] == toc[li][f], f"L{li+1} {f} mismatch"

    # extract & byte-compare each present section
    for li in range(LEVEL_COUNT):
        assets = asset_files_for_level(li)
        for si in range(5):
            if si == S_TRACK:
                blob = read_track_blob(li)
            else:
                blob = read_concat(assets.get(si, []))
            off = parsed[li][f"{SECTION_NAMES[si]}_off"]
            sz  = parsed[li][f"{SECTION_NAMES[si]}_size"]
            if blob is None:
                assert off == 0xFFFF and sz == 0
                continue
            start = off * SECTOR
            end   = start + sz * SECTOR
            chunk = pack[start:end]
            # source ends with implicit zero-pad in pack
            assert chunk[:len(blob)] == blob, f"L{li+1} {SECTION_NAMES[si]} data mismatch"
            # padding tail must be zeros
            assert all(b == 0 for b in chunk[len(blob):]), f"L{li+1} {SECTION_NAMES[si]} pad not zero"


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    pack, toc = build()
    OUT.write_bytes(pack)
    _verify(pack, toc)
    # Emit the pack size as an asm constant so the recursive loader can match
    # ZUMALVL.PAK by name AND exact size (kept in sync with every pack build).
    inc = ROOT / "Source" / "ASM" / "pak_size.inc"
    inc.write_text(
        "; Auto-generated by Source/OTHER/make_level_pack.py - do not edit by hand.\n"
        "; Expected size of ZUMALVL.PAK in bytes; the recursive loader matches the file\n"
        "; by name AND this exact size so it picks the current pack, not a stale copy.\n"
        f"EXPECTED_PAK_SIZE   EQU {len(pack)}\n",
        encoding="ascii",
        newline="\n",
    )
    print(f"pack: {OUT}  ({len(pack):,} bytes = {len(pack)//SECTOR} sectors)")
    print(f"  wrote {inc} (EXPECTED_PAK_SIZE={len(pack)})")
    print(f"layout:")
    print(f"  sector 0       header")
    print(f"  sector 1       TOC[{LEVEL_COUNT}] × 20 B")
    print(f"  sector 2..     data blob")
    print()
    present = 0
    absent  = 0
    for e in toc:
        sections = []
        for si in range(5):
            name = SECTION_NAMES[si]
            sz = e[f"{name}_size"]
            if sz > 0:
                sections.append(f"{name}={sz}s")
                present += 1
            else:
                absent += 1
        marker = "Y" if sections else "."
        print(f"  L{e['level']:02d} {marker}  {' '.join(sections) if sections else '(absent)'}")
    print()
    print(f"sections present={present}, absent={absent}")
    print(f"verification: PASS (byte-for-byte equal to source files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
