#!/usr/bin/env python3
"""Generate a dedicated 1024-native Cancun10 atlas for final-dialog stats.

This intentionally does not touch the pixel-tuned cancun8 menu/HUD font.
Only glyphs used by the final Win/Lose stats strings are packed. The source
640-space atlas is pre-scaled at build time to avoid runtime 1.6 bitmap scaling.
"""
from pathlib import Path
import subprocess

import numpy as np
from PIL import Image


ROOT = Path.home() / 'Desktop' / 'Zuma Deluxe VDAC2'
FONT_DIR = ROOT / 'Graphics' / 'fonts'
OUT_BIN = ROOT / 'Graphics' / 'Converted' / 'font_cancun10_stats_atlas.bin'
OUT_INC = ROOT / 'Source' / 'ASM' / 'font_cancun10_stats_meta.inc'

FONT_NAME = 'cancun10'
TARGET_H = 18           # 11 * 1.6, pre-rendered for 1024x768
USED_CHARS = list('ABCEHIMNORSTX0123456789:')
SPACE_WIDTH_SRC = 10
PREFIX = 'FONT_CANCUN10_STATS'
TABLE_PREFIX = 'font_cancun10_stats'


def parse_font_txt(path: Path):
    lines = path.read_text(encoding='utf-8').strip().splitlines()
    i = 0
    sections = {}
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith('CharList '):
            n = int(line.split()[1])
            sections['chars'] = [lines[i + 1 + j] or ' ' for j in range(n)]
            i += 1 + n
        elif line.startswith('WidthList '):
            n = int(line.split()[1])
            sections['widths'] = [int(lines[i + 1 + j]) for j in range(n)]
            i += 1 + n
        elif line.startswith('RectList '):
            n = int(line.split()[1])
            sections['rects'] = [tuple(int(v) for v in lines[i + 1 + j].split()) for j in range(n)]
            i += 1 + n
        else:
            i += 1
    return sections


def rgba_to_argb4_le_bytes(arr: np.ndarray) -> bytes:
    a16 = arr.astype(np.uint16)
    a4 = (a16[..., 3] >> 4) & 0xF
    r4 = (a16[..., 0] >> 4) & 0xF
    g4 = (a16[..., 1] >> 4) & 0xF
    b4 = (a16[..., 2] >> 4) & 0xF
    word = (a4 << 12) | (r4 << 8) | (g4 << 4) | b4
    return word.astype('<u2').tobytes()


def main():
    src = Image.open(FONT_DIR / f'{FONT_NAME}.png').convert('RGBA')
    src_h = src.size[1]
    meta = parse_font_txt(FONT_DIR / f'{FONT_NAME}.txt')
    char_index = {c: i for i, c in enumerate(meta['chars'])}
    rects = meta['rects']
    widths = meta['widths']

    scale = TARGET_H / src_h
    src = src.resize((round(src.size[0] * scale), TARGET_H), Image.Resampling.LANCZOS)
    src_arr = np.array(src)
    rects = [
        (round(rx * scale), round(ry * scale), max(1, round(rw * scale)), max(1, round(rh * scale)))
        for rx, ry, rw, rh in rects
    ]
    widths = [max(1, round(w * scale)) for w in widths]
    space_width = max(1, round(SPACE_WIDTH_SRC * scale))

    used = []
    cursor_x = 0
    glyph_x = [0] * 128
    glyph_w = [0] * 128
    advance = [0] * 128

    for ch in USED_CHARS:
        idx = char_index[ch]
        rx, ry, rw, rh = rects[idx]
        used.append((ch, cursor_x, rx, ry, rw, rh))
        c = ord(ch)
        glyph_x[c] = cursor_x
        glyph_w[c] = rw
        advance[c] = widths[idx]
        cursor_x += rw
    advance[ord(' ')] = space_width

    atlas_w = cursor_x
    atlas_h = TARGET_H
    atlas = np.zeros((atlas_h, atlas_w, 4), dtype=np.uint8)
    for ch, dx, rx, ry, rw, rh in used:
        atlas[:rh, dx:dx + rw] = src_arr[ry:ry + rh, rx:rx + rw]

    OUT_BIN.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(atlas, 'RGBA').save(ROOT / '_font_cancun10_stats_atlas_preview.png')
    atlas_bytes = rgba_to_argb4_le_bytes(atlas)
    if len(atlas_bytes) > 16384:
        raise SystemExit(f'atlas too large for one page: {len(atlas_bytes)}')
    OUT_BIN.write_bytes(atlas_bytes)

    for stale in OUT_BIN.parent.glob('font_cancun10_stats_atlas_p*.bin'):
        stale.unlink()
    for stale in OUT_BIN.parent.glob('font_cancun10_stats_atlas_p*_zx7.bin'):
        stale.unlink()

    page = atlas_bytes + b'\x00' * (16384 - len(atlas_bytes))
    raw_page = OUT_BIN.parent / 'font_cancun10_stats_atlas_p00.bin'
    zx7_page = OUT_BIN.parent / 'font_cancun10_stats_atlas_p00_zx7.bin'
    raw_page.write_bytes(page)
    subprocess.check_call(['python', str(Path(__file__).parent / 'compress_zx7.py'), str(raw_page), str(zx7_page)])

    with OUT_INC.open('w', encoding='utf-8') as f:
        f.write('; AUTO-GENERATED by make_font_cancun10_stats.py, do NOT edit.\n')
        f.write('; Compact 1024-native Win/Lose stats font. Charset from TIME/COMBOS/COINS/SCORE/MAX CHAIN/MAX COMBO.\n')
        f.write(f'{PREFIX}_W       EQU {atlas_w}\n')
        f.write(f'{PREFIX}_H       EQU {atlas_h}\n')
        f.write(f'{PREFIX}_STRIDE  EQU {atlas_w * 2}\n')
        f.write(f'{PREFIX}_BYTES   EQU {atlas_w * atlas_h * 2}\n')
        f.write(f'{PREFIX}_NUM_PAGES EQU 1\n\n')
        f.write(f'{TABLE_PREFIX}_glyph_x:\n')
        for c in range(0, 128, 8):
            f.write('    DEFW ' + ', '.join(str(glyph_x[c + i]) for i in range(8)) + '\n')
        f.write(f'\n{TABLE_PREFIX}_glyph_w:\n')
        for c in range(0, 128, 16):
            f.write('    DEFB ' + ', '.join(str(glyph_w[c + i]) for i in range(16)) + '\n')
        f.write(f'\n{TABLE_PREFIX}_advance:\n')
        for c in range(0, 128, 16):
            f.write('    DEFB ' + ', '.join(str(advance[c + i]) for i in range(16)) + '\n')

    print(f'{OUT_BIN.name}: {atlas_w}x{atlas_h}, {len(atlas_bytes)} bytes, zx7 {zx7_page.stat().st_size}')


if __name__ == '__main__':
    main()
