#!/usr/bin/env python3
"""Build ZUMAAUD.PAK for General Sound music.

For now the pack is the raw menu MOD file. The loader streams the exact byte
count from the FAT directory entry/auto-generated constants, so no wrapper bytes
are sent to GS.
"""
from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "Sounds" / "Converted" / "zuma_gs4_1mb_gssafe.mod"
OUT = ROOT / "Build" / "ZUMAAUD.PAK"
INC = ROOT / "Source" / "ASM" / "audio_pak_size.inc"
SECTOR = 512


def main() -> int:
    if not SRC.exists():
        raise SystemExit(f"missing audio source: {SRC}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(SRC, OUT)
    size = OUT.stat().st_size
    full_sectors, tail = divmod(size, SECTOR)
    total_sectors = full_sectors + (1 if tail else 0)
    INC.write_text(
        "; Auto-generated by Source/OTHER/make_audio_pack.py - do not edit by hand.\n"
        "; ZUMAAUD.PAK is the raw General Sound menu MOD stream.\n"
        f"EXPECTED_AUDIO_PAK_SIZE       EQU {size}\n"
        f"EXPECTED_AUDIO_PAK_SECTORS    EQU {total_sectors}\n"
        f"EXPECTED_AUDIO_PAK_FULL_SECS  EQU {full_sectors}\n"
        f"EXPECTED_AUDIO_PAK_TAIL_BYTES EQU {tail}\n",
        encoding="ascii",
    )
    print(f"audio pack: {OUT} ({size:,} bytes, {total_sectors} sectors, tail={tail})")
    print(f"  wrote {INC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
