"""Build ZUMALVL.PAK — external level pack streamed via WC ZiFi LOAD512.

Layout (512-byte sectors):
  Sector 0          : Header   { magic "ZLVP", version=1, level_count=22, sector_size=512 }
  Sector 1          : TOC[22]  × 20 bytes each (bg/pal/track/title/preview off+size)
  Sector 2..N       : data blob, per-level: bg -> pal -> track -> title -> preview
                      each section sector-aligned (zero-padded tail)
                      missing section => off=0xFFFF in TOC
                      two-track boards store track1 padded to 16K, then track2;
                      runtime loads page #06 + #0F from the same track section.

Currently:
  L01..L22              -> all five sections present when generated by
                           make_all_level_pack_assets.py

Pack lands in `Build/ZUMALVL.PAK`. Verified via internal _verify().
"""
from __future__ import annotations

import struct
import sys
from pathlib import Path
from typing import Optional

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
CONVERTED = ROOT / "Graphics" / "levels" / "Converted"
PACK_ASSETS = CONVERTED / "pack"
OUT = ROOT / "Build" / "ZUMALVL.PAK"

SECTOR = 512
LEVEL_COUNT = 22

# section indexes
S_BG, S_PAL, S_TRACK, S_TITLE, S_PREVIEW = range(5)
SECTION_NAMES = ["bg", "pal", "track", "title", "preview"]


def asset_files_for_level(level_idx0: int) -> dict[int, list[Path]]:
    """Return {section_index: [Path]} for level pack assets; empty dict if absent."""
    n = level_idx0 + 1
    return {
        S_BG:      [PACK_ASSETS / f"bg_l{n:02d}_paletted_p{p:02d}.bin" for p in range(8)],
        S_PAL:     [PACK_ASSETS / f"bg_l{n:02d}_palette_argb4.bin"],
        S_TRACK:   [PACK_ASSETS / f"track_l{n:02d}_640.bin"],
        S_TITLE:   [PACK_ASSETS / f"text_l{n:02d}_zx7.bin"],
        S_PREVIEW: [PACK_ASSETS / f"level_select_preview_l{n:02d}_p{p:02d}.bin" for p in range(8)],
    }


def track_files_for_level(level_idx0: int) -> list[Path]:
    n = level_idx0 + 1
    paths = [PACK_ASSETS / f"track_l{n:02d}_640.bin"]
    second = PACK_ASSETS / f"track_l{n:02d}_2_640.bin"
    if second.exists():
        paths.append(second)
    return paths


def read_concat(paths: list[Path]) -> Optional[bytes]:
    if not paths:
        return None
    blob = bytearray()
    for p in paths:
        if not p.exists():
            return None
        blob += p.read_bytes()
    return bytes(blob)


def sectors_for(size_bytes: int) -> int:
    return (size_bytes + SECTOR - 1) // SECTOR


def pad_to_sector(blob: bytes) -> bytes:
    pad = (-len(blob)) % SECTOR
    return blob + b"\x00" * pad


# --- track page-split -------------------------------------------------------
# A track sample is 6 bytes (X:u16, Y:u16, tangent:u8, flags:u8) after a 2-byte count
# header. The runtime reads samples from one 16K RAM page mapped at #8000, so a
# track longer than one page (>2730 samples) must be split on a SAMPLE boundary
# into two page-aligned chunks (no 5-byte record straddling #C000). chunkA holds
# the header + first TRACK_SAMPLES_PER_PAGE samples, zero-padded to a full 16K
# page; chunkB holds the rest with NO header (so sample i>=split lives at
# #8000 + (i-split)*6 on the next page). Tracks that fit one page are unchanged.
PAGE = 16384
TRACK_HDR = 2
TRACK_REC = 6
TRACK_SAMPLES_PER_PAGE = (PAGE - TRACK_HDR) // TRACK_REC   # = 2730

# --- 1024x768 upscale: scale stored sample X/Y x1.6 (640->1024, 480->768) ----
# Source track bins (track_l*_640.bin) stay in 640x480 space; we scale ONLY the
# coordinates packed into the PAK, so the running game gets 1024-space ball
# positions for free. Sample COUNT is unchanged -> VDC physics (speed in
# samples/frame, CELL_SIZE in samples) and tangent bytes are untouched, so the
# tuned feel is preserved exactly. Anything that consumes ball X/Y at runtime
# (bullet collision, frog, killzone) must also be in 1024-space.
TRACK_SCALE_NUM = 8     # x1.6 = 8/5
TRACK_SCALE_DEN = 5


def scale_track_samples(blob: Optional[bytes]) -> Optional[bytes]:
    """Return a track blob (header + N*6) with X,Y scaled x8/5, rounded."""
    if blob is None:
        return None
    count = struct.unpack_from("<H", blob, 0)[0]
    out = bytearray(blob[:TRACK_HDR])
    off = TRACK_HDR
    for _ in range(count):
        x, y, tan, flags = struct.unpack_from("<hhBB", blob, off)
        x = int(round(x * TRACK_SCALE_NUM / TRACK_SCALE_DEN))
        y = int(round(y * TRACK_SCALE_NUM / TRACK_SCALE_DEN))
        out += struct.pack("<hhBB", x, y, tan, flags)
        off += TRACK_REC
    return bytes(out)


def pagesplit_track(blob: Optional[bytes]) -> Optional[bytes]:
    if blob is None:
        return None
    count = struct.unpack_from("<H", blob, 0)[0]
    if count <= TRACK_SAMPLES_PER_PAGE:
        return blob
    cut = TRACK_HDR + TRACK_SAMPLES_PER_PAGE * TRACK_REC      # end of sample 3275
    chunk_a = blob[:cut] + b"\x00" * (PAGE - cut)            # pad to full page
    chunk_b = blob[cut:]                                      # samples 3276.., no header
    return chunk_a + chunk_b


def read_track_blob(level_idx0: int) -> Optional[bytes]:
    paths = track_files_for_level(level_idx0)
    if not paths or not paths[0].exists():
        return None
    first = scale_track_samples(paths[0].read_bytes())
    if len(paths) == 1:
        return pagesplit_track(first)

    # Multi-curve boards in the original game have two independent short paths.
    # Keep the old TOC intact: page 1 is the first track, page 2 is the second.
    second = scale_track_samples(paths[1].read_bytes())
    if len(first) > PAGE or len(second) > PAGE:
        raise ValueError(
            f"L{level_idx0 + 1:02d}: two-track runtime requires each track <= 16K "
            f"(got {len(first)} and {len(second)} bytes)"
        )
    return first + b"\x00" * (PAGE - len(first)) + second


def build() -> tuple[bytes, list[dict]]:
    # Stage 1: read all assets, compute per-level section sizes
    level_data: list[list[Optional[bytes]]] = []
    for li in range(LEVEL_COUNT):
        assets = asset_files_for_level(li)
        row: list[Optional[bytes]] = []
        for si in range(5):
            if si == S_TRACK:
                blob = read_track_blob(li)
            else:
                blob = read_concat(assets.get(si, []))
            row.append(blob)
        level_data.append(row)

    # Stage 2: layout — assign sector offsets, in order: header(1) + toc(1) + data
    cursor = 2  # first data sector after header(0) + toc(1)
    toc: list[dict] = []
    for li, row in enumerate(level_data):
        entry = {"level": li + 1}
        for si in range(5):
            name = SECTION_NAMES[si]
            blob = row[si]
            if blob is None:
                entry[f"{name}_off"]  = 0xFFFF
                entry[f"{name}_size"] = 0
            else:
                size_sec = sectors_for(len(blob))
                entry[f"{name}_off"]  = cursor
                entry[f"{name}_size"] = size_sec
                cursor += size_sec
        toc.append(entry)

    # Stage 3: emit bytes
    out = bytearray()
    # sector 0: header
    header = bytearray(SECTOR)
    header[0:4] = b"ZLVP"
    header[4]   = 1                 # version
    header[5]   = LEVEL_COUNT
    struct.pack_into("<H", header, 6, SECTOR)
    out += bytes(header)

    # sector 1: TOC
    toc_blob = bytearray()
    for e in toc:
        toc_blob += struct.pack(
            "<HHHHHHHHHH",
            e["bg_off"], e["bg_size"],
            e["pal_off"], e["pal_size"],
            e["track_off"], e["track_size"],
            e["title_off"], e["title_size"],
            e["preview_off"], e["preview_size"],
        )
    out += pad_to_sector(bytes(toc_blob))
    assert len(out) == 2 * SECTOR, f"header+toc != 1024, got {len(out)}"

    # sectors 2..N: data blob in TOC order
    for li, row in enumerate(level_data):
        for si in range(5):
            blob = row[si]
            if blob is None:
                continue
            out += pad_to_sector(blob)

    return bytes(out), toc


def _verify(pack: bytes, toc: list[dict]) -> None:
    """Re-extract each level section, byte-compare against source files."""
    # magic
    assert pack[0:4] == b"ZLVP"
    assert pack[4] == 1
    assert pack[5] == LEVEL_COUNT
    assert struct.unpack_from("<H", pack, 6)[0] == SECTOR

    # parse TOC straight from pack
    parsed = []
    base = SECTOR  # sector 1
    for li in range(LEVEL_COUNT):
        vals = struct.unpack_from("<HHHHHHHHHH", pack, base + li * 20)
        parsed.append({
            "bg_off": vals[0], "bg_size": vals[1],
            "pal_off": vals[2], "pal_size": vals[3],
            "track_off": vals[4], "track_size": vals[5],
            "title_off": vals[6], "title_size": vals[7],
            "preview_off": vals[8], "preview_size": vals[9],
        })

    # cross-check vs builder's toc
    for li in range(LEVEL_COUNT):
        for f in ("bg_off","bg_size","pal_off","pal_size","track_off","track_size",
                  "title_off","title_size","preview_off","preview_size"):
            assert parsed[li][f] == toc[li][f], f"L{li+1} {f} mismatch"

    # extract & byte-compare each present section
    for li in range(LEVEL_COUNT):
        assets = asset_files_for_level(li)
        for si in range(5):
            if si == S_TRACK:
                blob = read_track_blob(li)
            else:
                blob = read_concat(assets.get(si, []))
            off = parsed[li][f"{SECTION_NAMES[si]}_off"]
            sz  = parsed[li][f"{SECTION_NAMES[si]}_size"]
            if blob is None:
                assert off == 0xFFFF and sz == 0
                continue
            start = off * SECTOR
            end   = start + sz * SECTOR
            chunk = pack[start:end]
            # source ends with implicit zero-pad in pack
            assert chunk[:len(blob)] == blob, f"L{li+1} {SECTION_NAMES[si]} data mismatch"
            # padding tail must be zeros
            assert all(b == 0 for b in chunk[len(blob):]), f"L{li+1} {SECTION_NAMES[si]} pad not zero"


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    pack, toc = build()
    OUT.write_bytes(pack)
    _verify(pack, toc)
    # Emit the pack size as an asm constant so the recursive loader can match
    # ZUMALVL.PAK by name AND exact size (kept in sync with every pack build).
    inc = ROOT / "Source" / "ASM" / "pak_size.inc"
    inc.write_text(
        "; Auto-generated by Source/OTHER/make_level_pack.py - do not edit by hand.\n"
        "; Expected size of ZUMALVL.PAK in bytes; the recursive loader matches the file\n"
        "; by name AND this exact size so it picks the current pack, not a stale copy.\n"
        f"EXPECTED_PAK_SIZE   EQU {len(pack)}\n",
        encoding="ascii",
    )
    print(f"pack: {OUT}  ({len(pack):,} bytes = {len(pack)//SECTOR} sectors)")
    print(f"  wrote {inc} (EXPECTED_PAK_SIZE={len(pack)})")
    print(f"layout:")
    print(f"  sector 0       header")
    print(f"  sector 1       TOC[{LEVEL_COUNT}] × 20 B")
    print(f"  sector 2..     data blob")
    print()
    present = 0
    absent  = 0
    for e in toc:
        sections = []
        for si in range(5):
            name = SECTION_NAMES[si]
            sz = e[f"{name}_size"]
            if sz > 0:
                sections.append(f"{name}={sz}s")
                present += 1
            else:
                absent += 1
        marker = "Y" if sections else "."
        print(f"  L{e['level']:02d} {marker}  {' '.join(sections) if sections else '(absent)'}")
    print()
    print(f"sections present={present}, absent={absent}")
    print(f"verification: PASS (byte-for-byte equal to source files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
