#pragma once

/*
  Generated by ft812_dxt_convert_v2.py.

  Format: DXT1_L4_RGB565

  RAM_G raw layout:
    c0 RGB565 layer + c1 RGB565 layer + FT_L4 mask

  FT812 display-list helper notes:
    - color bitmap handle points to c0+c1 RGB565 cells
    - cell 0 = c0
    - cell 1 = c1
    - mask bitmap handle points to L2/L4 mask
    - first draw mask so it writes alpha
    - then draw c1 with DST_ALPHA
    - then draw c0 with ONE_MINUS_DST_ALPHA
*/

#define Q_TINY_L4_WIDTH 64
#define Q_TINY_L4_HEIGHT 64
#define Q_TINY_L4_BLOCKS_X 16
#define Q_TINY_L4_BLOCKS_Y 16
#define Q_TINY_L4_C0_OFFSET 0
#define Q_TINY_L4_C1_OFFSET 512
#define Q_TINY_L4_MASK_OFFSET 1024
#define Q_TINY_L4_C0_SIZE 512
#define Q_TINY_L4_C1_SIZE 512
#define Q_TINY_L4_MASK_SIZE 2048
#define Q_TINY_L4_RAW_SIZE 3072
#define Q_TINY_L4_COLOR_STRIDE 32
#define Q_TINY_L4_COLOR_HEIGHT 16
#define Q_TINY_L4_MASK_STRIDE 32
#define Q_TINY_L4_FORMAT_TYPE 2
#define Q_TINY_L4_MASK_FORMAT FT_L4
