"""Generate per-page signatures so F2-dump can identify de-facto page mapping
of every memory slot at runtime.

For each page used by spgbld_vdac2.ini we write 2 bytes at offset #3FFE
within that page:
  byte 0 = page number (low byte)
  byte 1 = 0xA5    (magic marker)

When dumping a frozen state, we read the last 2 bytes of each 16K slot:
  dump[0x3FFE], dump[0x7FFE], dump[0xBFFE], dump[0xFFFE]

If byte 1 is 0xA5, byte 0 tells us which physical page is mapped there.
If byte 1 is not 0xA5, the slot is mapped to a page that does not belong
to our SPG (e.g. WC residency, or some inflate source we lost track of).

Also prints SPG `Block` declarations the user can paste into
spgbld_vdac2.ini, OR call this script with --inject to append them.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
INI = ROOT / "spgbld_vdac2.ini"
SIG_DIR = ROOT / "Build" / "sig"

SIG_MARKER_BYTE = 0xA5
# spgbld requires 512-aligned Block offsets. We use #3E00 (last 512-aligned
# slot before page end), writing a 512-byte file where bytes 0..509 = 0x00
# and bytes 510..511 = (page#, 0xA5). The 2-byte signature lands at #3FFE.
SIG_BLOCK_OFFSET = 0x3E00
SIG_FILE_SIZE = 512
SIG_AT_END = SIG_FILE_SIZE - 2          # 510
BLOCK_MARK_START = "; === PAGE SIGNATURES (auto-generated by make_page_signatures.py) ==="
BLOCK_MARK_END = "; === END PAGE SIGNATURES ==="


def parse_used_pages(ini_path: Path) -> set[int]:
    pages: set[int] = set()
    rx = re.compile(r"^\s*Block\s*=\s*[^,]+,\s*#?([0-9A-Fa-f]+)\s*,", re.I)
    for line in ini_path.read_text(encoding="utf-8", errors="replace").splitlines():
        line_no_comments = line.split(";", 1)[0]
        m = rx.match(line_no_comments)
        if m:
            pages.add(int(m.group(1), 16))
    return pages


def write_sig_files(pages: set[int]) -> None:
    SIG_DIR.mkdir(parents=True, exist_ok=True)
    for p in pages:
        blob = bytearray(SIG_FILE_SIZE)            # all zeros
        blob[SIG_AT_END]     = p & 0xFF             # page number
        blob[SIG_AT_END + 1] = SIG_MARKER_BYTE      # 0xA5 marker
        (SIG_DIR / f"sig_p{p:02X}.bin").write_bytes(bytes(blob))


def build_block_lines(pages: set[int]) -> list[str]:
    out: list[str] = []
    out.append(BLOCK_MARK_START)
    out.append(
        f"; Each block writes 512 bytes at offset #{SIG_BLOCK_OFFSET:04X}. The"
    )
    out.append(
        f"; last 2 bytes of that block (offset #3FFE in slot view) = (page, #A5)."
    )
    out.append(
        f"; F2-dump reading slot tail #3FFE/#7FFE/#BFFE/#FFFE identifies mapping."
    )
    out.append(
        f"; NOTE: this overwrites last 512 bytes of any asset on the same page;"
    )
    out.append(
        f"; revert (remove this section) after diagnostic dump is captured."
    )
    for p in sorted(pages):
        rel = f"Build/sig/sig_p{p:02X}.bin"
        out.append(f"Block = #{SIG_BLOCK_OFFSET:04X}, #{p:02X}, {rel}")
    out.append(BLOCK_MARK_END)
    return out


def inject_into_ini(ini_path: Path, block_lines: list[str]) -> tuple[int, int]:
    text = ini_path.read_text(encoding="utf-8", errors="replace")

    # strip previous auto-block if any (idempotent)
    start_idx = text.find(BLOCK_MARK_START)
    end_idx = text.find(BLOCK_MARK_END)
    if start_idx != -1 and end_idx != -1:
        # remove from start of START line to end of END line + newline
        # walk back to start of line
        ls = text.rfind("\n", 0, start_idx) + 1
        le = text.find("\n", end_idx)
        if le == -1:
            le = len(text)
        text = text[:ls] + text[le + 1 :]
        removed = end_idx - start_idx
    else:
        removed = 0

    sep = "" if text.endswith("\n") else "\n"
    appended = sep + "\n" + "\n".join(block_lines) + "\n"
    text += appended

    ini_path.write_text(text, encoding="utf-8")
    return removed, len(appended)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--inject", action="store_true",
                    help="modify spgbld_vdac2.ini to add signature blocks")
    args = ap.parse_args()

    pages = parse_used_pages(INI)
    print(f"used pages in {INI.name}: {len(pages)}")
    print(f"  pages: {', '.join(f'#{p:02X}' for p in sorted(pages))}")

    write_sig_files(pages)
    print(f"wrote {len(pages)} signature files to {SIG_DIR}")

    block_lines = build_block_lines(pages)

    if args.inject:
        removed, added = inject_into_ini(INI, block_lines)
        print(f"updated {INI.name} (-{removed} +{added} bytes)")
    else:
        print()
        print("Append manually to spgbld_vdac2.ini, OR re-run with --inject:")
        print("---")
        for line in block_lines:
            print(line)
        print("---")
    return 0


if __name__ == "__main__":
    sys.exit(main())
