#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
INI = ROOT / "spgbld_vdac2.ini"
OUT_PAK = ROOT / "Build" / "ZUMAMAIN.PAK"
OUT_INC = ROOT / "Source" / "ASM" / "main_pak_table.inc"
PAGE_SIZE = 0x4000
SECTORS_PER_PAGE = PAGE_SIZE // 512

# Pages that must already exist in the small boot SPG and must survive
# ZUMAMAIN.PAK loading. Temporary boot artwork pages are intentionally not
# listed here: ZUMAMAIN.PAK reloads those page numbers with the real game data.
BOOT_PAGES = {0x00, 0x05, 0x25, 0x26, 0x27, 0x40, 0x41}

BLOCK_RE = re.compile(
    r"^\s*Block\s*=\s*(#[0-9A-Fa-f]+|0x[0-9A-Fa-f]+|\d+)\s*,\s*"
    r"(#[0-9A-Fa-f]+|0x[0-9A-Fa-f]+|\d+)\s*,\s*(.*?)\s*$"
)


def num(text: str) -> int:
    text = text.strip()
    if text.startswith("#"):
        return int(text[1:], 16)
    return int(text, 0)


def parse_blocks() -> list[tuple[int, int, Path, int]]:
    out: list[tuple[int, int, Path, int]] = []
    for line in INI.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.split(";", 1)[0]
        m = BLOCK_RE.match(line)
        if not m:
            continue
        addr = num(m.group(1))
        page = num(m.group(2))
        rel = Path(m.group(3).strip().replace("/", "\\"))
        src = ROOT / rel
        size = src.stat().st_size if src.exists() else PAGE_SIZE
        if addr:
            if page not in BOOT_PAGES:
                out.append((page, addr, rel, 0))
            continue
        chunks = max(1, (size + PAGE_SIZE - 1) // PAGE_SIZE)
        for chunk in range(chunks):
            chunk_page = page + chunk
            if chunk_page in BOOT_PAGES:
                continue
            out.append((chunk_page, 0, rel, chunk))
    return out


def write_table(blocks: list[tuple[int, int, Path, int]]) -> None:
    lines = [
        "; Auto-generated by Source/OTHER/make_main_pack.py --table",
        "MAIN_PAK_SECTORS_PER_PAGE EQU 32",
        f"MAIN_PAK_PAGE_COUNT EQU {len(blocks)}",
        "MainPakPageTable:",
    ]
    sector = 0
    for page, _addr, rel, chunk in blocks:
        lines.append(f"                DEFB #{page:02X}")
        lines.append(f"                DEFW {sector}")
        suffix = f" chunk {chunk}" if chunk else ""
        lines.append(f"                ; {rel.as_posix()}{suffix}")
        sector += SECTORS_PER_PAGE
    lines.append("")
    OUT_INC.write_text("\n".join(lines), encoding="utf-8")


def read_page(path: Path, addr: int, chunk: int) -> bytes:
    data = path.read_bytes()
    if addr:
        # SPGBLD places the bytes at address inside the 16K page.
        off = addr & (PAGE_SIZE - 1)
        if off + len(data) > PAGE_SIZE:
            raise RuntimeError(f"{path} does not fit page at offset {off:#x}")
        return (b"\x00" * off + data).ljust(PAGE_SIZE, b"\x00")
    start = chunk * PAGE_SIZE
    return data[start:start + PAGE_SIZE].ljust(PAGE_SIZE, b"\x00")


def write_pack(blocks: list[tuple[int, int, Path, int]]) -> None:
    OUT_PAK.parent.mkdir(parents=True, exist_ok=True)
    blob = bytearray()
    for page, addr, rel, chunk in blocks:
        src = ROOT / rel
        if not src.exists():
            raise FileNotFoundError(f"page #{page:02X}: missing {src}")
        blob += read_page(src, addr, chunk)
    OUT_PAK.write_bytes(blob)
    print(f"wrote {OUT_PAK}: {len(blocks)} pages, {len(blob)} bytes")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--table", action="store_true")
    ap.add_argument("--pack", action="store_true")
    ns = ap.parse_args()
    blocks = parse_blocks()
    if ns.table:
        write_table(blocks)
        print(f"wrote {OUT_INC}: {len(blocks)} entries")
    if ns.pack:
        write_pack(blocks)
    if not ns.table and not ns.pack:
        ap.error("use --table and/or --pack")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
